### ISSUE TITLE
Unable to build VS2017/VS2019/Ubuntu images with Packer versions >1.3.4

### ISSUE THREAD

**Issue by kaylangan** [microsoft/azure-pipelines-image-generation#929] opened 2019-05-09 14:26 UTC
See https://github.com/microsoft/azure-pipelines-image-generation/issues/913#issuecomment-490022570

**Describe the bug**
Unable to build VS2019 image with Packer versions >1.3.4. Works with Packer v1.3.4.

**Expected behavior**
Successful build, or at least document the Packer version required.

**Actual behavior**
Failed build.

**Image impacted**
VS2017/VS2019

**Comment by NateB2** [comment] 2019-05-09 20:42
I ran into this too, and tracked down the bug to an issue in Packer: https://github.com/hashicorp/packer/issues/7608

Apparently there's a regression that causes Chocolatey to hang while downloading packages.

**Comment by kaylangan** [comment] 2019-05-15 00:34
Once this is resolved, we need to revert the changes introduced in #942 to document that Packer 1.3.4 or earlier must be used.

**Comment by mikemorris** [comment] 2019-06-18 23:09
It looks like this was fixed in https://github.com/hashicorp/packer/pull/7579, released in Packer v1.4.1

**Closed** 2019-07-03 21:06 UTC
