### ISSUE TITLE
 [HOSTED MAC]Xamarin iOS: 12.2.1.11 and Mono MDK 15.6.0.221

### ISSUE THREAD

**Issue by ngalicoco** [Microsoft/azure-pipelines-image-generation#529] opened 2018-12-06 21:06 UTC
# Help us route

We need to below mentioned tools to be updated on HostedMac, for us to continue using it. As these version fixes bugs that are required in our enterprise application. I have monitoring the mac image read me, but it hasn't been updated since a month after Xamarin released stable versions.

## Tool info
- Tool name: Xamarin.iOS and  Mono MDK
- Add or update? Update
- Desired version Xamarin iOS: 12.2.1.11
- Desired version Mono MDK: 15.6.0.221
- If this is an add request:
  - Brief description of tool: N/A
  - URL for tool's homepage: N/A
  - Open source license type (Apache, MIT, GPL, etc.): N/A

## Areas and ecosystems

- [x] iOS, macOS, and Apple-specific tools
- [x] Xamarin

## Hosted pools
- [x] macOS

**Comment by winterdouglas** [comment] 2018-12-10 12:05
I'm here to +1  the above request and to mention that it's really necessary to be prioritized since the 3rd party libraries are starting to be built against the newer versions of Xamarin.iOS and Azure DevOps still doesn't support it.

Currently we have faced problems with PdfTron and Lottie as well due to these outdated things when building on the pipeline. Locally everything works smoothly.

**Comment by jasonctoms** [comment] 2019-01-07 17:06
I think when there are major Xamarin or VS updates they should be coordinated so the agents can update as well.  It has been almost a full month since iOS app builds have worked on the hosted MacOS agent if you are working with VS 7.7+ for Mac.  Hopefully the update happens soon, but if every VS update breaks automated builds, then the hosted agents aren't very useful.

**Comment by winterdouglas** [comment] 2019-01-07 23:19
Agreed 100%, I'm still waiting for that and it seems no one is taking a look at it. The issue I've opened they simply deleted the conversation and set as new, which for me indicates it need votes. As I said, for me it should be prioritized since without these changes the CI is useless for the ones using VS 7.7.

**Comment by nrajpurkar** [comment] 2019-01-07 23:22
Hi there, the team is actively working on getting the VS 7.7 related updates in. I can assure you we're looking at this and it will be available soon. Thanks for your patience!

**Comment by jasonctoms** [comment] 2019-01-14 09:54
I noticed today that the hosted MacOS agent has been updated with VS 7.7 and Mono 5.16.0.  I was hoping this would fix the issue, but when I try to manually set the correct SDK as recommended [here,](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=vsts&tabs=designer#xamarin) the build task gives the error message 
`MSBuild or xbuild (Mono) were not found on the macOS or Linux agent.`

**Comment by winterdouglas** [comment] 2019-01-15 09:32
> I noticed today that the hosted MacOS agent has been updated with VS 7.7 and Mono 5.16.0. I was hoping this would fix the issue, but when I try to manually set the correct SDK as recommended [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=vsts&tabs=designer#xamarin) by running the bash command
> `sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_16_0`
> the build task gives the error message
> `MSBuild or xbuild (Mono) were not found on the macOS or Linux agent.`

I tried the same here by running:
```
SYMLINK=5_16_0
MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"

sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_16_0
```

and for me it fails on the nuget restore with the message that Mono was not found.

**Comment by aweFalafelApps** [comment] 2019-01-17 13:46
Worked for me by adding an extra 0 to the Mono version number:
`/bin/bash -c "sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_16_0_0"`

However now I'm getting an error about the Xcode version:
`MTOUCH : error MT0091: This version of Xamarin.iOS requires the iOS 12.1 SDK (shipped with Xcode 10.1).`

and the script used to set that doesn't seem to change anything:
`/bin/bash -c "sudo xcode-select -s /Applications/Xcode_10.1.app/Contents/Developer"`

**Comment by ngalicoco** [comment] 2019-01-17 21:48
After following what @aweFalafelApps  suggested, our builds succeeded and deployed to App Center with no problems. Although our QA team is still testing things that were broken with previous versions of iOS SDK's and fixed in 5.16.0, Fingers crossed. I will update this thread with final result. Thanks to azure team for finally doing this. I hope they will update them as soon as Xamarin releases new versions.

**Comment by madhurig** [comment] 2019-01-17 21:54
@aweFalafelApps Some toolsets in Xamarin, will only use xcode from the standard default path /Applications/Xcode.app (e.g. lipo) and running xcode-select will not help. 

You can try adding a script at the beginning of your pipeline to see if that helps you:

```
echo move xcode
mv /Applications/Xcode.app /Applications/Xcode_9.4.1_tmp.app
mv /Applications/Xcode_10.1.app /Applications/Xcode.app

```

**Comment by aweFalafelApps** [comment] 2019-01-17 22:30
@ngalicoco did you have to do anything specific to get the proper Xcode version selected?

**Comment by ngalicoco** [comment] 2019-01-17 22:34
> @ngalicoco did you have to do anything specific to get the proper Xcode version selected?

Ours is a Xamarin Forms solution. None of our build tasks in the pipeline sets any sought of Xcode version.

**Comment by aweFalafelApps** [comment] 2019-01-17 22:48
Strange, the script from @madhurig did the trick. But without it the build fails because it couldn't find the appropriate iOS sdk. So I wonder why it is working for @ngalicoco. Regardless, we're up and running. Thanks madhurig!!!

**Comment by winterdouglas** [comment] 2019-01-17 22:54
I guess what you need is the script I sent on a comment above just adjusting the version as you suggested:

SYMLINK=5_16_0_0
MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"

sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh $SYMLINK

I tested it on my environment and it worked well.

**Comment by madhurig** [comment] 2019-01-18 14:40
@aweFalafelApps - The script I provided was something I found helped workaround this Xamarin issue: https://github.com/xamarin/xamarin-macios/issues/3931. Basically the toolset is not honoring the path of Xcode set by xcode-select but needs a separate setting in Visual Studio for Mac. The default is /Applications/Xcode.app. The script is switching that up to the version we want. This is not the official way supported by Xcode, so we are treating this as a workaround.

**Comment by ngalicoco** [comment] 2019-01-24 13:46
We are facing issues when trying to aim our iOS project to Xamarin.iOS 12.1 SDK
As per the azure hosted mac image generation doc, Mono 5.16 should be selecting 12.1 SDK, but looks like it is not.
error : The iOS SDK version '12.1' is not installed, and no newer version was found
I am selecting Mono 5.16.0 version before building the iOS project.
This is blocking us from using azure pipeline to build and deploy to Test Flight, as the apple review emailed us 
----------------------------------------------------------
We identified one or more issues with a recent delivery for your app, "CoConstruct". Your delivery was successful, but you may wish to correct the following issues in your next delivery:

SDK Version Issue - This app was built with the iOS 11.4 SDK. Starting March 2019, all iOS apps submitted to the App Store must be built with the iOS 12.1 SDK or later, included in Xcode 10.1 or later.
-----------------------------------------------------------
Links to similar issues raised in the community
https://developercommunity.visualstudio.com/content/problem/433836/hosted-mac-agents-dosent-have-apple-sdk-121-instal.html

**Comment by nrajpurkar** [comment] 2019-01-24 19:55
Hi there, the team is taking a look into this.

**Comment by KarinBerg** [comment] 2019-01-31 20:00
Is there any news about this issue?

**Comment by Miraclemax99** [comment] 2019-02-01 16:19
I had success building for the iOS 12.1 SDK when I incorporated the command line task discussed by Matthias Raymann here:
https://developercommunity.visualstudio.com/content/problem/433836/hosted-mac-agents-dosent-have-apple-sdk-121-instal.html

**Comment by KarinBerg** [comment] 2019-02-19 11:32
@nrajpurkar Any news about that issue? The mentioned workaround is working but for me the question is when the root cause will be fixed?

**Comment by nrajpurkar** [comment] 2019-02-19 18:49
@KarinBerg please take a look at the updates we made in [our documentation ](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=designer#xamarin) that should fix this issue

**Closed by nrajpurkar** 2019-02-19 18:49 UTC
Labels: area:Xamarin/Mono, image:macOS, issue:Enhancement

**Comment by KarinBerg** [comment] 2019-02-22 09:12
Sorry, to bother you again. But after testing again the MacOS Agent I understood that you did not really fix the problem. The workaround is now the intended solution, right? But why is that? It worked before without applying some bash scripts. What is the reason for sticking with that “solution”? Sorry, but for me that is not plausible and satisfying at the moment. Could you make it more transparent why the problem can’t be really fixed?

Thanks in advanced
Karin
