### ISSUE TITLE
Xamarin: Add Mono 5.16.0.179 (macOS)

### ISSUE THREAD

**Issue by DavidStaheli** [Microsoft/azure-pipelines-image-generation#490] opened 2018-11-21 17:48 UTC
Xamarin: Add Mono 5.16.0.179 (macOS)

**Comment by AngleOSaxon** [comment] 2018-12-17 14:56
Is there a timeline for when this might get installed?

There's a bug in versions 5.08 through 5.12 of the Mono HTTP libraries that's affecting one of my projects.  The issue is fixed in v5.16, and I'd like to be able to switch to it.

**Comment by nrajpurkar** [comment] 2018-12-17 18:31
Hi @AngleOSaxon, we are currently working on updating to Mono 5.16.0.220. At this time, I don't have a hard ETA to share.

**Comment by travismartinjones** [comment] 2019-03-29 12:53
@nrajpurkar Do you have an updated ETA to share?

**Comment by AngleOSaxon** [comment] 2019-03-29 14:17
I believe the update occurred in January--it just ended up being referenced in #529 (see [this comment](https://github.com/Microsoft/azure-pipelines-image-generation/issues/529#issuecomment-453949732)) instead of here.

In order to use the new version successfully, I did have to add a Bash Script Task to my pipeline, containing the following: 

```
SYMLINK=5_16_0_0
MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"
```

This needs to execute before the Build task, to ensure that Xamarin finds the right Mono libraries.

**Closed** 2019-04-11 20:50 UTC
Labels: area:Xamarin/Mono, image:macOS, issue:Enhancement
