### ISSUE TITLE
The term 'powershell.exe' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by tiagodenoronha** [Microsoft/azure-pipelines-image-generation#217] opened 2018-08-31 10:58 UTC
Good afternoon,

When running a build in which the only step is an inline PowerShell command (Write-Host), I get an error when running on Windows machines (Hosted or Hosted VS2017):

![image](https://user-images.githubusercontent.com/27889458/44908849-fb305500-ad14-11e8-8172-e438f989e080.png)

When running on the MacOS build machine, it runs fine.

### Steps to Reproduce
Create an empty build definition.
Select Hosted or Hosted VS2017.
Add the PowerShell task.
Select Inline.
Trigger the build definition.

**Comment by TNoronha** [comment] 2018-09-06 10:59
Hello,
Yes, this is the logs I have:

2018-09-06T10:57:43.8218727Z ##[section]Starting: GetJsonMapping
2018-09-06T10:57:43.8223062Z ==============================================================================
2018-09-06T10:57:43.8223227Z Task         : PowerShell
2018-09-06T10:57:43.8223393Z Description  : Run a PowerShell script on Windows, macOS, or Linux.
2018-09-06T10:57:43.8223890Z Version      : 2.136.0
2018-09-06T10:57:43.8224071Z Author       : Microsoft Corporation
2018-09-06T10:57:43.8224266Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613736)
2018-09-06T10:57:43.8224477Z ==============================================================================
2018-09-06T10:57:45.6258025Z Generating script.
2018-09-06T10:57:46.2285947Z ##[error]The term 'powershell.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
2018-09-06T10:57:46.2681873Z ##[section]Finishing: GetJsonMapping


My only inline command is a "Write-Host".

**Comment by lokesh755** [comment] 2018-09-06 16:04
Can you provide full job log ?

**Comment by TNoronha** [comment] 2018-09-06 18:20
That's the full job log. I can provide you with the agent log if you wish.

**Comment by vtbassmatt** [comment] 2018-10-10 18:20
@tiagodenoronha I'm sorry for the delay, I didn't see this one. Are you still seeing this issue? I can't repro it.

**Comment by tiagodenoronha** [comment] 2018-10-17 23:02
Hey no problem! I'll give the builds a try again and let you know! :)

**Comment by DavidStaheli** [comment] 2019-02-18 18:45
Closing this now that we can't reproduce it.  Otherwise, please feel free to reopen it.

**Closed by DavidStaheli** 2019-02-18 18:45 UTC
Labels: area:Scripting/command line, image:VS2015-Win2012r2, image:VS2017-Win2016, issue:Bug report

**Comment by alsulli** [comment] 2020-07-16 19:24
Came across this today, found that this error can be reproduced if you have a variable named "path". If you Write-Host $(path) it will throw this error. Name your variables something else and give it a try. @tiagodenoronha

**Comment by tiagodenoronha** [comment] 2020-07-16 21:27
Hmm need to get back to this and try it, thanks for the info!
