### ISSUE TITLE
vs2017-win2016 Nuget Restore Bug in UWP project that references .Net Standard 2.0 project

### ISSUE THREAD

**Issue by andygikling** [Microsoft/azure-pipelines-image-generation#509] opened 2018-12-03 03:16 UTC
# Nuget Restore Bug in UWP project that references .Net Standard 2.0 project (vs2017-win2016).

## Description
I've got a relatively simple Xamarin solution that compiles my UWP application correctly under Visual Studio 2017 version 15.9.3 on my desktop.

Using vs2017-win2016 vmImage in an Azure DevOps Pipelines the step "NuGetCommand@2" fails to restore - here's a snip of the yml

    - task: NuGetToolInstaller@0
    - task: NuGetCommand@2
       inputs:
         restoreSolution: '**/MyProjectName.sln'

## Expected Behavior
The expected behavior is that Azure DevOps Pipeline should be able to restore my packages before building.

## Actual Behavior
Instead, I receive an error. 

The following was output from my MyProjectName.UWP.csproj project (MyProjectName.csproj is the NetStandard 2.0 project the UWP project depends on):

[error]The nuget command failed with exit code(1) and error(NU1201: Project MyProjectName is not compatible with uap10.0.17763 (UAP,Version=v10.0.17763). Project MyProjectName supports: netstandard2.0 (.NETStandard,Version=v2.0)

But uap10.0.17763 does support .Net Standard 2.0.

This is suspiciously like the error discussed here: https://github.com/dotnet/standard/issues/462#issuecomment-336207924

However, the tools on my desktop computer restore the packages perfectly.  Something about the environment in vs2017-win2016 seems goofy.  I've noticed MSBuild is older on the vmImage but I'm not sure that explains it.  Note the comment in the above related issue by Amenti - he fixed the issue by reinstalling some of the tools in a different order.

Anyone got any ideas?  What should I try next?

**Comment by eriawan** [comment] 2018-12-12 16:40
@andygikling 

FYI, current VM image of VS2017 hosted agent is still using VS 2017 15.8.2.

This is my today's manual build log:

![image](https://user-images.githubusercontent.com/8773147/49884270-0728c880-fe67-11e8-940c-e5508ecd76ad.png)

And this version of VS 2017 doesn't have Windows SDK 17763 installed yet.

This issue is similar to my issue #499 on request to upgrade VS 2017 to have 15.9.1.

**Comment by eriawan** [comment] 2018-12-12 17:03
@lokesh755 

GREAT NEWS! I really want this update, especially for this issue and my #499 too!

I hope the image is ready at least tomorrow, so I could start to use it early 🙂

**Comment by alexmullans** [comment] 2018-12-12 18:47
You will most likely also want to add a version input to your `NuGetToolInstaller`:
```
  inputs:
    versionSpec: '4.9.2'
```

**Comment by Gert-Cominotto** [comment] 2019-01-09 08:36
Is there any update on this issue?

**Comment by alexmullans** [comment] 2019-01-25 18:23
@DavidStaheli can we close this as a duplicate of #449? Can I also get perms to this repo so I can tag and close issues?

**Comment by DavidStaheli** [comment] 2019-02-01 00:44
As suggested, closing this as a duplicate of #449.  @alexmullans you should receive an email invite for permissions on this repo.

**Closed by DavidStaheli** 2019-02-01 00:44 UTC
Labels: area:Artifacts, image:VS2017-Win2016, issue:Bug report
