### ISSUE TITLE
Add macOS Mojave 10.15

### ISSUE THREAD

**Issue by dsteenman** [microsoft/azure-pipelines-image-generation#1411] opened 2019-11-22 11:00 UTC
**Tool information**
- Tool name: macOS
- Add or update? Add
- Desired version: 10.15

Noticed when updating my vmImage from macOS-10.14 to macOS-10.15 in azure pipelines that the image doesn't exist yet:

`##[Warning 1]
An image label with the label macOS-10.15 does not exist. `

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [x] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
macOS 10.15

**Hosted Pools**
- [x] macOS
- [ ] Ubuntu
- [ ] Windows

**Comment by kaylangan** [comment] 2019-11-22 21:13
Dupe of #1277

**Closed by kaylangan** 2019-11-22 21:13 UTC
