### ISSUE TITLE
Windows PHP Startup: Unable to load dynamic library 'curl' and 'mbstring'

### ISSUE THREAD

**Issue by andyli** [microsoft/azure-pipelines-image-generation#990] opened 2019-06-01 09:17 UTC
**Describe the bug**
Simply running `php --version` would print warnings about curl and mbstring extensions not found.

**Expected behavior**
No warning message.

**Actual behavior**

Example build log from [my build](https://dev.azure.com/onthewings/GitHub%20public%20projects/_build/results?buildId=49&view=logs&lineStart=12&jobId=92f38c5a-9166-5edb-492c-b1eb3738def5&taskId=ee7f0d65-fc2d-55a4-168c-59a46890f400):
```
##[error]PHP Warning:  PHP Startup: Unable to load dynamic library 'curl' (tried: C:\php\ext\curl (The specified module could not be found.), C:\php\ext\php_curl.dll (The specified module could not be found.)) in Unknown on line 0
##[error]PHP Warning:  PHP Startup: Unable to load dynamic library 'mbstri
##[error]n
##[error]g
##[error]'
##[error] 
##[error](
##[error]t
##[error]r
##[error]i
##[error]e
##[error]d
##[error]:
##[error] 
##[error]C
##[error]:
##[error]\
##[error]p
##[error]h
##[error]p
##[error]\
##[error]e
##[error]x
##[error]t
##[error]\
##[error]m
##[error]b
##[error]s
##[error]t
##[error]r
##[error]i
##[error]n
##[error]g
##[error] 
##[error](
##[error]T
##[error]h
##[error]e
##[error] 
##[error]s
##[error]p
##[error]e
##[error]c
##[error]i
##[error]f
##[error]i
##[error]e
##[error]d
##[error] 
##[error]m
##[error]o
##[error]d
##[error]u
##[error]l
##[error]e
##[error] 
##[error]c
##[error]o
##[error]u
##[error]l
##[error]d
##[error] 
##[error]n
##[error]o
##[error]t
##[error] 
##[error]b
##[error]e
##[error] 
##[error]f
##[error]o
##[error]u
##[error]n
##[error]d
##[error].
##[error])
##[error],
##[error] 
##[error]C
##[error]:
##[error]\
##[error]p
##[error]h
##[error]p
##[error]\
##[error]e
##[error]x
##[error]t
##[error]\
##[error]p
##[error]h
##[error]p
##[error]_
##[error]m
##[error]b
##[error]s
##[error]t
##[error]r
##[error]i
##[error]n
##[error]g
##[error].
##[error]d
##[error]l
##[error]l
##[error] 
##[error](
##[error]T
##[error]h
##[error]e
##[error] 
##[error]s
##[error]p
##[error]e
##[error]c
##[error]i
##[error]f
##[error]i
##[error]e
##[error]d
##[error] 
##[error]m
##[error]o
##[error]d
##[error]u
##[error]l
##[error]e
##[error] 
##[error]c
##[error]o
##[error]uld not be found.)) in Unknown on line 0
```

**Image impacted**

Tested windows-2019, I expect it affects other windows images as well.

**Comment by andyli** [comment] 2019-06-01 09:45
The log suggested php tried to load extensions from `C:\php\ext`, but php was installed in `c:\tools\php` according to:

https://github.com/microsoft/azure-pipelines-image-generation/blob/0a1acf90bb71673ae6e6e8bfe827a851130d417a/images/win/scripts/Installers/Install-PHP.ps1#L11

**Comment by alepauly** [comment] 2019-06-10 13:39
@andyli thanks for details, we're looking into it.

**Comment by alepauly** [comment] 2019-06-28 14:58
The issue is fixed in master and currently rolling out in the latest version of the Azure Pipelines hosted images.

**Closed by alepauly** 2019-06-28 14:58 UTC
Labels: area:PHP, image:VS2019
