### ISSUE TITLE
Inconsistent behavior of 'Hosted Ubuntu 1604' Host image

### ISSUE THREAD

**Issue by carct** [Microsoft/azure-pipelines-image-generation#185] opened 2018-08-03 07:24 UTC
Hi,

As per advice from [here](https://github.com/Microsoft/vsts-agent/issues/1744), opening an issue under this repo.

OS of the machine running the agent? OSX/Windows/Linux/...
pool "Hosted Ubuntu 1604"

What's not working?
Please include error messages and screenshots.
Running task 'Bash' (Run a Bash script on macOS, Linux, or Windows // Version: 3.136.0) with the following in-line script:
_sudo apt-get update
sudo apt-get -y install software-properties-common
sudo apt-add-repository ppa:ansible/ansible
sudo apt-get update
sudo apt-get -y install ansible
sudo pip install --upgrade pip
sudo pip install ansible[azure]
sudo pip install pywinrm
ansible --version_

**Sometimes** i get the following message:
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
..................
The directory '/home/vsts/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/vsts/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

I can see that advice regarding -H flag, but the troubling thing is that the above behavior is totally inconsistent as the above happens only sometimes, most of the other times it works just fine with the exact same in-line script.
This makes me think that maybe the mentioned flag is not actually the issue as in the logs of the successful execution i don't see the first part of the message related to the 'dpkg lock / resource temp unavailable', but i still see the second part that advises me to use -H flag to sudo and, once again, everything works just fine.

What are your thoughts on the matter ?

Thank you,
Andrei

**Comment by dakale** [comment] 2018-08-07 13:40
How often is this occuring? Half the time, or more or less? Have you tried the Hosted Linux Preview pool as well? There are a couple difference between the two that may help narrow down what the issue is. Unfortunately I am not sure what could be causing this but will investigate

**Comment by carct** [comment] 2018-08-07 15:59
at the beginning it was quite rare but after a day of tests or so it started to be more often

i didn't try the Hosted Linux Preview because i thought that actually the Hosted Ubuntu is a newer version (GA)
i can give it a couple of tries tomorrow, if u consider it helpful, let's say 10 runs on each pool

thanks for having an eye on it!

**Comment by timotheeguerin** [comment] 2018-09-12 22:27
I am having the same issue too since I try to move to the new pool.vmImage naming.
Use to have 
`queue: Hosted Linux Preview`

now this is failing ~1/3 times
```yaml
pool:
      vmImage: ubuntu-16.04
```

Log from one is 
```
2018-09-12T22:21:59.0492439Z ##[section]Starting: Install Linux packages
2018-09-12T22:21:59.0618841Z ==============================================================================
2018-09-12T22:21:59.0637288Z Task         : Command Line
2018-09-12T22:21:59.0650968Z Description  : Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
2018-09-12T22:21:59.0665503Z Version      : 2.136.0
2018-09-12T22:21:59.0679398Z Author       : Microsoft Corporation
2018-09-12T22:21:59.0693102Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
2018-09-12T22:21:59.0707313Z ==============================================================================
2018-09-12T22:22:01.5679508Z Generating script.
2018-09-12T22:22:01.5854377Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/3fb6ce12-fad2-4c7c-b788-4c549a4f7113.sh
2018-09-12T22:22:02.2659290Z Ign:2 http://dl.google.com/linux/chrome/deb stable InRelease
2018-09-12T22:22:02.3056819Z Hit:3 http://azure.archive.ubuntu.com/ubuntu xenial InRelease
2018-09-12T22:22:02.3085182Z Hit:4 http://dl.google.com/linux/chrome/deb stable Release
2018-09-12T22:22:02.3141824Z Hit:5 http://azure.archive.ubuntu.com/ubuntu xenial-updates InRelease
2018-09-12T22:22:02.3519094Z Hit:6 http://azure.archive.ubuntu.com/ubuntu xenial-backports InRelease
2018-09-12T22:22:02.4139662Z Hit:7 http://security.ubuntu.com/ubuntu xenial-security InRelease
2018-09-12T22:22:02.4162719Z Hit:8 http://ppa.launchpad.net/git-core/ppa/ubuntu xenial InRelease
2018-09-12T22:22:02.6121725Z Hit:10 https://packages.microsoft.com/repos/azure-cli xenial InRelease
2018-09-12T22:22:02.6148830Z Hit:1 https://packages.cloud.google.com/apt kubernetes-xenial InRelease
2018-09-12T22:22:02.6389984Z Hit:12 http://ppa.launchpad.net/ondrej/php/ubuntu xenial InRelease
2018-09-12T22:22:02.6429337Z Hit:13 https://packages.microsoft.com/ubuntu/16.04/prod xenial InRelease
2018-09-12T22:22:02.6678415Z Hit:14 https://download.mono-project.com/repo/ubuntu stable-xenial InRelease
2018-09-12T22:22:02.7265064Z Hit:15 https://cli-assets.heroku.com/apt ./ InRelease
2018-09-12T22:22:02.8228777Z Ign:9 http://packages.erlang-solutions.com/debian xenial InRelease
2018-09-12T22:22:02.8604328Z Hit:16 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu xenial InRelease
2018-09-12T22:22:03.1318974Z Hit:17 http://packages.erlang-solutions.com/debian xenial Release
2018-09-12T22:22:03.2606591Z Hit:18 https://packagecloud.io/github/git-lfs/ubuntu xenial InRelease
2018-09-12T22:22:06.3150039Z Reading package lists...
2018-09-12T22:22:06.3750713Z E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
2018-09-12T22:22:06.3813085Z E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
2018-09-12T22:22:06.3994573Z ##[error]Bash exited with code '100'.
2018-09-12T22:22:06.4644665Z ##[section]Finishing: Install Linux packages
```

**Comment by dakale** [comment] 2018-09-14 15:52
I am having trouble reproducing this. Is `apt-get` the very first thing that you are executing in your build?

**Comment by timotheeguerin** [comment] 2018-09-14 16:02
Yes. Though I have nested templates.

This is the step I have.
```yaml
  - script: |
      set -e
      apt-get update
      apt-get install -y libxkbfile-dev pkg-config libsecret-1-dev libxss1 libgconf-2-4 dbus xvfb libgtk-3-0 rpm
```

Code is here https://github.com/Azure/BatchExplorer/tree/feature/signing-vsts/.vsts
I reverted to linux preview though for now.

**Comment by dakale** [comment] 2018-09-14 17:17
(related info here: https://github.com/boxcutter/ubuntu/issues/73)
It seems like there are systemd units that run apt update when the machine comes online that is overlapping with the start of builds. Depending on scheduling, and how early in your build you run apt, there can be contention. 

I am testing removing these systemd units during image generation. 

@timotheeguerin In the meantime another reported workaround is to simply sleep (I know, not great) before running apt update. Something like 10-15 seconds seems to work. But weigh that against migrating to Linux Preview, maybe it will be better for you

I will work on a fix and update when I believe its resolved

**Comment by SymphonicJohn** [comment] 2018-09-18 15:43
I am getting the same inconsistent behavior. Timing does not appear to be the problem, apt is run after a couple minutes of other steps in the build.

Has anyone found a solution or workaround?

**Comment by timotheeguerin** [comment] 2018-09-18 15:49
For now I am using `queue: Hosted Linux Preview` instead of the `ubuntu 16` pool one which doesn't seem to have this issue.

**Comment by peterdanis** [comment] 2018-09-18 17:47
For me the Hosted Linux Preview image also helped. I am using the `pool` config. Part of my yaml config:
~~~~
jobs:
  - job: Linux
    timeoutInMinutes: 15
    pool:
      name: Hosted Linux Preview
    steps:
      - task: .......
.....
~~~~

**Comment by schultetwin1** [comment] 2018-09-18 23:54
I'm also seeing this same issue on the ubuntu 16 pool. It seems to have just started recently

**Comment by dakale** [comment] 2018-09-19 01:04
Yes I believe so. Seems to correspond with higher load on Ubuntu pools (recent LSI) causing more builds to get scheduled against machines that are just coming online, hence the package lock race

**Comment by bryanmacfarlane** [comment] 2018-09-19 01:06
@dakale - that makes sense.

**Comment by kalkun** [comment] 2018-09-21 07:35
Same issue here.
It seems there is a race for the lock. If I remove the locks as the first thing I get to see that it fails installing `PHP7.0-*`, which are not dependencies I have in my build.

[Here is my log](https://pastebin.com/raw/BmEi1Ksz)

**Comment by dakale** [comment] 2018-09-21 13:41
Hi @kalkun What script are you running to "Remove any inherited apt locks"? 

I deployed a fix yesterday to remove the on-startup automatic apt updates, which I believe were locking the dpkg/lock file. Try rerunning your build without the lock-removing phase and let me know if the issue persists

**Comment by dakale** [comment] 2018-09-26 17:04
This should be fixed now, by: https://github.com/Microsoft/azure-pipelines-image-generation/commit/a1f27961f28e8a8f39f4eed27e81fddfe8caf05a#diff-7bbecaa0a2b1999de4d1ebdc3f1206cdR62

**Closed by dakale** 2018-09-26 17:04 UTC

**Comment by patvin80** [comment] 2019-03-01 03:06
Continue to experience the same issue.

I have copied the samples for a build directory from https://docs.microsoft.com/en-us/azure/devops/pipelines/process/service-containers?view=azure-devops&tabs=yaml

But none of the samples work and infact each of them gives the same error
For my first pipeline:
```
steps:
  - script: |
      sudo apt-get install -y postgresql-client
      psql --host=postgres --username=postgres --command="SELECT 1;"
```
In one case I get 

> sudo command not found.

When I remove sudo I get
```
steps:
  - script: |
      apt-get install -y postgresql-client
      psql --host=postgres --username=postgres --command="SELECT 1;"
```

> [command]/bin/bash --noprofile --norc /__w/_temp/06e1eb79-4952-49af-831c-7de0d8bbd116.sh
> E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
> E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?

**Comment by dakale** [comment] 2019-03-01 15:49
@patvin80 I think that is a different issue. Are you using a container via [container jobs?](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml)

If you are using Hosted Ubuntu without a container, `sudo` will be present so it seems like you must be. In that case, your container just does not have `sudo` installed. The standard ubuntu images do not have it, so you would need to use one that does or build your own

**Comment by patvin80** [comment] 2019-05-07 21:02
@dakale the examples is the place where I copied it from and not able to get it to work in a pipeline. I understand that will not be able to do Sudo but then what are my options for installing the postgres client?
