### ISSUE TITLE
Azure Pipelines hosted Vs2017-Server2016 do not contain python 3.7.4

### ISSUE THREAD

**Issue by SLdragon** [microsoft/azure-pipelines-image-generation#1350] opened 2019-10-25 09:11 UTC
Hi, team, from the document, it said that it should contain python 3.7.4,
![image](https://user-images.githubusercontent.com/5545529/67558726-185e8900-f74a-11e9-8316-babd48780260.png)

However, I got the errors below, any ideas about this?
```
##[error]Version spec 3.7.4 for architecture x86 did not match any version in Agent.ToolsDirectory.
Versions in C:/hostedtoolcache/windows:
2.7.16 (x86)
3.4.4 (x86)
3.5.4 (x86)
3.6.8 (x86)
3.7.5 (x86)
3.8.0 (x86)
2.7.16 (x64)
3.4.4 (x64)
3.5.4 (x64)
3.6.8 (x64)
3.7.5 (x64)
3.8.0 (x64)
If this is a Microsoft-hosted agent, check that this image supports side-by-side versions of Python at https://aka.ms/hosted-agent-software.
If this is a self-hosted agent, see how to configure side-by-side Python versions at https://go.microsoft.com/fwlink/?linkid=871498.
Finishing: Use Python 3.7.4
```

**Comment by alepauly** [comment] 2019-10-29 20:35
@SLdragon the document is changed with every new image deployment. It's possible that we didn't update it on a timely manner. Can you share a link of the branch you see that in? Also, you can inspect the ```ImageVersion``` variable in the agent to see the exact version and then go to the release branch to see the actual contents of that version.

Not saying that's definitely the reason but if you can inspect that variable and confirm that the version is documented to have 3.7.4 that would help us investigate if the doc and VM are out of sync. Thanks!

**Comment by SLdragon** [comment] 2019-10-30 01:38
Thank you @alepauly for your feedback, 
Because our pipeline sometimes want to use fixed python version to make it more stable, however, when agent updated, then the old python version would missing and could break the pipeline, so are there some others ways to achive this without breaking the build, thanks!

**Comment by alepauly** [comment] 2019-11-07 13:33
@SLdragon apologies for the delay here. I'll ask the team that owns our Python installs to chime in here.

**Comment by Prachiti9** [comment] 2019-11-07 15:53
@SLdragon the best practice is to use just major version (3) or major.minor version (3.8) and not subversion. Subversions reflect mostly bug fixes. 
About docs, agents are updated frequently to make sure we support latest versions as soon as possible I wouldnt be surprise if there was lag in doc updates. I will take a note about keeping docs in sync with agent updates.

**Comment by SLdragon** [comment] 2019-11-12 01:29
Thank you Prachiti9 and alepauly, we will use 3.7.x instead, thanks!

**Comment by StingyJack** [comment] 2019-11-12 14:03
@alepauly - This same thing burned me with python 3.6.7 being dropped, without notice, and without choice. Builds just started failing. It just happened again with NodeJs jumping two major versions. 

@Prachiti9 - Are you part of this product team? If so, docs and notifications need to precede changes to the build agents by at least two weeks.

**Comment by alepauly** [comment] 2019-12-04 22:14
@StingyJack - I'm part of the product team dealing with the docs and changes to the images in the hosted agents and I agree,  we need to get better at communicating expectations about the image contents and upcoming changes to critical pieces. We are actively working on it. Thanks.

**Comment by alepauly** [comment] 2019-12-04 22:16
Closing this as it seems resolved. @SLdragon please let us know if you still need resolution. Thanks for reaching out.

**Closed by alepauly** 2019-12-04 22:16 UTC

**Comment by StingyJack** [comment] 2019-12-05 00:37
@alepauly - whatever you figure out has to be better than the Bring Your Own image idea that was floating around a few weeks ago. Personally I don't see the problem with just versioning the images and letting us update at our own pace. It's not going to be that much storage space to retain each used image version, and I would really appreciate not spending a half day or weekend every few weeks figuring out what program or dependency can be be updated to now appease the build agent and not require a bunch of regression testing.
