### ISSUE TITLE
Strange race condition when using apt-get in Ubuntu 1604 agnet

### ISSUE THREAD

**Issue by chrisrpatterson** [Microsoft/azure-pipelines-image-generation#238] opened 2018-09-14 13:41 UTC
numba/numba#3309

**Comment by dakale** [comment] 2018-09-14 15:43
Related, possible duplicate of: https://github.com/Microsoft/azure-pipelines-image-generation/issues/185

**Comment by dakale** [comment] 2018-09-26 17:04
Fixed by https://github.com/Microsoft/azure-pipelines-image-generation/commit/a1f27961f28e8a8f39f4eed27e81fddfe8caf05a#diff-7bbecaa0a2b1999de4d1ebdc3f1206cdR62

**Closed by dakale** 2018-09-26 17:04 UTC
