### ISSUE TITLE
Pre-installed Boost is occasionaly missing from VS2017 image

### ISSUE THREAD

**Issue by taketwo** [Microsoft/azure-pipelines-image-generation#849] opened 2019-04-10 19:08 UTC
At PCL we are eager (https://github.com/PointCloudLibrary/pcl/pull/2935) to start using pre-installed Boost on Windows VS2017 agents. However, we can not make this transition yet; occasionally Boost is missing from the image that the agent runs.

Originally I though that this may be due to slow deployment of newly released images to agents and will be solved within a few days. But it's been more than three weeks that I am monitoring our builds and Boost is still sometimes missing. For example, here is [today's build](https://dev.azure.com/PointCloudLibrary/pcl/_build/results?buildId=2999) (see x64 job). There is a "print environment variables" step, and one can see that there is no `BOOST_ROOT` variable there, so Boost is not available.

Any ideas what's wrong? When can we expect Boost to be consistently available on all agents?

**Comment by joebourneMS** [comment] 2019-04-11 19:54
@shadyysf @alepauly This smells as if not all pools have the same version of the VS2017 image. Can we do a first investigation pass here to confirm if that is true or not? If we're on all the same versions, we can engage C++ ecosystem owners.

CC @kaylangan

**Comment by alepauly** [comment] 2019-04-11 20:08
@taketwo - thanks for reporting the problem. Looks like there was a deployment issue causing some machines with the old image (without pre-installed Boost) to stick around and serve jobs. I'll let you know when it's fixed.
cc @joebourneMS, @shadyysf

**Comment by alepauly** [comment] 2019-04-15 18:51
@taketwo - The issue is fixed now, all of the agents running the VS2017 image are up to date. Thanks!

**Closed by alepauly** 2019-04-15 18:51 UTC

**Comment by taketwo** [comment] 2019-04-16 07:59
Great, thank you!
