### ISSUE TITLE
[macOS] Target Android v10.0 causes build to fail 

### ISSUE THREAD

**Issue by vincentcastagna** [microsoft/azure-pipelines-image-generation#1377] opened 2019-11-05 19:17 UTC
**Describe the bug**

- Using image macOS-10.14 throw  ` error XA0000: Could not determine API level for $(TargetFrameworkVersion) of 'v10.0'.

For windows it seems like image name is **windows-2019** . 

**Expected behavior**

- Using macOS-10-14 should be able to build targetting 10.0

Isn't it supposed to be supported as of today ? 
- For macOS it is supposed to support SDK 29 as stated in the [README ](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md)

**Actual behavior**

Check this build on UnoPlatform for more info (Android_Test job & documentation job) :
https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=9294

**Image impacted**
- macOS-10-14

**Comment by maxim-lobanov** [comment] 2019-11-06 16:28
Hi @vincentcastagna,
Based on your YAML file, you are trying to use Xamarin bundle `5_18_1` to build your app. This bundle contains Xamarin.Android 9.2 and probably it is root cause of the issue.
To fix the issue, you need to set bundle `6_4_0` which contains Xamarin.Android 10.0.

Small contribution from my side: https://github.com/unoplatform/uno/pull/2037
It fixes initial issue but produces other errors that seems to be related to code:
```
Mixins/Android/FrameworkElementMixins.g.cs(6122,18): error CS0114: 'ProgressRing.MinWidth' hides inherited member 'ProgressBar.MinWidth'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword. [/Users/runner/runners/2.160.0/work/1/s/src/Uno.UI/Uno.UI.csproj]
```

**Comment by vincentcastagna** [comment] 2019-11-06 18:45
@maxim-lobanov 

That's awesome. Thank you very much for your time !

**Comment by maxim-lobanov** [comment] 2019-11-07 10:56
I am closing the issue. Feel free to reopen if needs

**Closed by maxim-lobanov** 2019-11-07 10:56 UTC

**Comment by justinhorner** [comment] 2020-02-27 20:08
Just a heads up to anyone else who might come across this...this stopped working for our builds this morning.  We had been using macOS-10.14, xCode 11.2.1 and mono 6.4.0 since mid-Dec 2019 but between 8am and 10am MST today, the Android builds starting failing with this error: Could not determine API level for $(TargetFrameworkVersion) of 'v10.0'.

We were able to get the builds going again by upgrading everything (macOS -> 10.15, mono -> 6.6, xCode -> 11.3.1).

Not sure what changed though...
