### ISSUE TITLE
Unable to build VS2017 image 

### ISSUE THREAD

**Issue by KasireddyAlekhya** [microsoft/azure-pipelines-image-generation#913] opened 2019-05-07 04:55 UTC
**Describe the bug**
Running packer image generation using https://github.com/Microsoft/azure-pipelines-image-generation within Azure PowerShell.

**Expected behavior**
Successful generation of VS2017 image.
**Actual behavior**

PowerShell script was structed after few hours.

  1. Step 1 : Run the below script 
"C:\Users\v-alkas\Documents\GitHub\azure-pipelines-image-generation" 
GenerateResourcesAndImage.
2. Step 2
Given Image, subscription ,Imagegenerationrepositoryroot and location .. details

Script structed in below 
**vhd: Downloading Bootstrapper ...
    vhd: Starting Install ...
    vhd: Installation successful
    vhd: Visual Studio version VisualStudio/15.9.11+28307.586 installed
==> vhd: Restarting Machine
==> vhd: Waiting for machine to restart...
==> vhd: #< CLIXML
    vhd: pkrvmfti4p0lq8d restarted.
==> vhd: Machine successfully restarted, moving on
==> vhd: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> vhd: Pausing 2m0s before the next provisioner...
==> vhd: Provisioning with Powershell...
==> vhd: Provisioning with powershell script: C:\Users\v-alkas\Documents\GitHub\azure-pipelines-image-generation\images\win/scripts/Installers/Vs2017/Install-SSDT.ps1
    vhd: Downloading SSDT-Setup-ENU.exe...
    vhd: Starting Install SSDT-Setup-ENU.exe...
    vhd: Installation successful
==> vhd: Restarting Machine
==> vhd: Waiting for machine to restart...
    vhd: pkrvmfti4p0lq8d restarted.
==> vhd: #< CLIXML
==> vhd: Machine successfully restarted, moving on
==> vhd: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> vhd: Provisioning with Powershell...
==> vhd: Provisioning with powershell script: C:\Users\v-alkas\Documents\GitHub\azure-pipelines-image-generation\images\win/scripts/Installers/Vs2017/Install-Wix.ps1
    vhd: Chocolatey v0.10.13
    vhd: Installing the following packages:
    vhd: wixtoolset
    vhd: By installing you accept licenses for the packages.
Progress: Downloading DotNet3.5 3.5.20160716... 100%**

**Image impacted**
Windows 2016 - VS2017

![1](https://user-images.githubusercontent.com/44359532/57272447-648d1280-70b1-11e9-9637-94d92e8c100d.PNG)
[logs_packer1.4.0.txt](https://github.com/microsoft/azure-pipelines-image-generation/files/3150835/logs_packer1.4.0.txt)

**Comment by Andreas-Huber** [comment] 2019-05-07 10:17
I can confirm that the Windows 2019 - VS2019 image has the exact same issue. I tried it twice.

After the packer script got stuck, I also tried to manually install it on the same VM with `choco install wixtoolset -y --force`. But chocolatey states, that the wixtoolset has already been installed.

So it seems to me that the installation is working, but somehow packer (v1.4.0) got stuck.

**Comment by kaylangan** [comment] 2019-05-07 18:30
Does the image build if you use Packer 1.3.4 or earlier?

**Comment by KasireddyAlekhya** [comment] 2019-05-08 04:23
I have tried with packer1.3.4 still I am not able to create the image.

**please find the attachment for logs and screenshot

[logs_packer1.3.4.txt](https://github.com/microsoft/azure-pipelines-image-generation/files/3155485/logs_packer1.3.4.txt)
![packer1 3 4](https://user-images.githubusercontent.com/44359532/57349257-088cc180-7177-11e9-9445-840ca36d1aed.PNG)
![image](https://user-images.githubusercontent.com/44359532/57349273-180c0a80-7177-11e9-9668-8e69545a0eb0.png)

**Comment by Andreas-Huber** [comment] 2019-05-09 08:53
Packer v1.3.4 did the trick for me with the Windows 2019 - VS2019 image.

**Comment by kaylangan** [comment] 2019-05-09 14:26
@Andreas-Huber I created a new issue to track the issue with the VS2019 image since it appears it might be different from the VS2017 one. See #929

**Comment by KasireddyAlekhya** [comment] 2019-05-10 04:58
Used packer 1.3.4  I am able to create Image without any issue

**Comment by kaylangan** [comment] 2019-05-10 13:51
@KasireddyAlekhya Got it, thanks. I'm going to close this in favor of #929. Appears this is a regression in packer.

**Closed by kaylangan** 2019-05-10 13:51 UTC
