### ISSUE TITLE
Unable to build Win Server2016 VS2017 image - after running for 6 hours

### ISSUE THREAD

**Issue by nreddipalle** [microsoft/azure-pipelines-image-generation#795] opened 2019-03-18 22:30 UTC
**Describe the bug**
Running packer image generation using https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/vs2017-Server2016-Azure.json within Azure Devops. failed after running for 6 hours.
![image](https://user-images.githubusercontent.com/28302399/54567872-aea82080-49ab-11e9-98de-b8c2cd7603bb.png)

**Expected behavior**
Successful generation of VS2017 image.

**Actual behavior**
A description with steps to reproduce the issue.

- vcredist140 (exited 1638) - Error while running 'C:\ProgramData\chocolatey\lib\vcredist140\tools\chocolateyInstall.ps1'.

https://support.microsoft.com/en-us/help/4092997/vc-2015-redistributable-install-error-1638-when-newer-version-present says the error occurs if newer version already exists. Anyone getting similar exception??

**Image impacted**
Windows 2016 - VS2017

Also, any suggestions on the vm_size to use. I am currently using Standard_DS4_v2

**Comment by nreddipalle** [comment] 2019-03-19 13:54
To add more notes, this issue is occurring during install of OpenSSL via https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/scripts/Installers/Install-OpenSSL.ps1 which is trying to install via chocolatey https://chocolatey.org/packages/OpenSSL.Light which has a dependency of vcredist140 (≥ 14.12.25810)

**Comment by joebourneMS** [comment] 2019-03-19 18:24
Hello,
I am a Program Manager on the Hosted Pipelines Infrastructure team, we own the image gen process as well as the architecture powering our hosted builds. Unfortunately, you're not going to be able to build the images using Hosted Azure Pipelines. There is a global 6 hour time-out on our hosted builds, and our image gen process just flat out takes longer than that.

You'll need to do something similar to what we do and have a local private agent and build the image yourself. Sorry this isn't a cleaner experience today!

**Comment by nreddipalle** [comment] 2019-03-19 18:30
Hello,
Thanks. I am building the image using my own VM installing packer there but using the existing Json file from here: https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/vs2017-Server2016-Azure.json. Can't I use it that way??

**Comment by nreddipalle** [comment] 2019-03-19 21:03
@joebourneMS ??

**Comment by 4deeptech** [comment] 2019-03-27 01:20
@joebourneMS I cloned this repo locally and tried to build the same one as @nreddipalle and got the same error with vcredist140.  It did not time out and I am not running it in Pipelines. The only reason I am even trying to do this is because the 3 Hosted pipelines I am paying for are all failing with connection issues: "The agent: [agent name] lost communication with the server. Verify the machine is running and has a healthy network connection".

**Comment by joebourneMS** [comment] 2019-03-27 13:55
Re-opening this issue and we will investigate. Stay tuned

**Comment by 4deeptech** [comment] 2019-03-27 14:00
@joebourneMS @riezebosch has a PR out there for it #806

**Comment by 4deeptech** [comment] 2019-03-27 19:12
@joebourneMS And oneget.org is down so the Initialize-VM.ps1 fails at:

Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force

![image](https://user-images.githubusercontent.com/1807644/55105353-556e7a00-509a-11e9-9a90-5d70c02dd535.png)

**Comment by riezebosch** [comment] 2019-03-28 07:24
> Hello @joebourneMS
> Thanks. I am building the image using my own VM installing packer there but using the existing Json file from here: https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/vs2017-Server2016-Azure.json. Can't I use it that way?? I am using DevOps only for spinning the VM and passing in the json file. My main issue is the error it is causing during the build but not the duration.

You most definitely should check out my extension to ease the process: https://marketplace.visualstudio.com/items?itemName=riezebosch.Packer

**Comment by joebourneMS** [comment] 2019-04-01 13:03
It looks like the PR to fix this was never merged. Having team look into it now.

**Comment by ArchSerpo** [comment] 2019-05-01 01:44
Any update on this @joebourneMS ?

I have encountered this issue myself after cloning the repo today, it was hung on install Chocolatey for a couple hours before I came across this issue

**Comment by joebourneMS** [comment] 2019-05-01 12:53
Which image are you hitting this on? VS2017?

**Comment by ArchSerpo** [comment] 2019-05-01 23:08
Yep VS2017 

I also had an issue with VS2019 when installing VSIX, it got to "Downloading NET365 100%" or similar and did nothing for an hour. I believe I saw this in another issue yesterday but cannot find the ticket now

**Comment by kaylangan** [comment] 2019-05-15 00:41
@nreddipalle @4deeptech @ArchSerpo what version of Packer are you using? Can you try using 1.3.4 or earlier? There appears to have been a regression in Packer. We're tracking this in #929.

**Closed** 2019-05-15 00:48 UTC
Labels: Area:Images, issue:Bug report
