### ISSUE TITLE
Add Python 3.8 on macOS

### ISSUE THREAD

**Issue by ethomson** [microsoft/azure-pipelines-image-generation#1372] opened 2019-11-03 15:49 UTC
Python 3.8 is available on the ubuntu and windows runners, but is not yet available on macOS.

**Tool information**
- Tool name: python 3.8
- Add or update? add
- Desired version: 3.8
- If this is an add request:
  - Brief description of tool: Python language
  - URL for tool's homepage: https://www.python.org/

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [X] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
macOS-latest

**Workaround**

**Are you willing to submit a PR?**
maybe

**Comment by BrianMouncer** [comment] 2019-11-05 01:30
Same request foradding Python 3.8 support, but on all agents, not just MacOS.
We use python on these hosted agents: Hosted Ubuntu 1604, Hosted VS2017, and Hosted MacOS.

Please add Python support for all agents that python supports for python 3.8.

**Comment by kaylangan** [comment] 2019-11-08 23:09
Dupe of https://github.com/microsoft/azure-pipelines-image-generation/issues/1317

**Closed by kaylangan** 2019-11-08 23:09 UTC
