### ISSUE TITLE
Rust (cargo, rustc) sometimes missing in Ubuntu 16.04 images

### ISSUE THREAD

**Issue by technosophos** [microsoft/azure-pipelines-image-generation#1024] opened 2019-06-19 16:28 UTC
**Describe the bug**
About 25% of the time, my Azure Pipelines builds fail because the Rust toolchain cannot be found. The rest of the time, it works fine. Often, simply re-running the build will fix the issue.

My azure-pipelines.yml file is as follows:

```yaml
pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    cargo version
    rustc --version
    cargo test
  displayName: 'Run unit tests'
```

**Expected behavior**
Azure Pipelines invocations should have the same tools available for every build.

**Actual behavior**
Builds fail ~25% of the time with the following error:
<img width="810" alt="Screen Shot 2019-06-18 at 14 52 23" src="https://user-images.githubusercontent.com/89193/59783115-a7c7cd00-927c-11e9-9f8b-f631cef4ce98.png">

**Image impacted**
ubuntu

**Comment by johnterickson** [comment] 2019-06-19 16:39
Related to #1012

**Comment by technosophos** [comment] 2019-06-19 20:58
I just checked agent versions on both failing and non-failing tests, in case it was a simple version mismatch. But both are agent version `2.151.1`

**Comment by technosophos** [comment] 2019-06-19 20:59
For reference, here's a screenshot of the frontmatter of a successful run:

<img width="808" alt="Screen Shot 2019-06-19 at 14 58 57" src="https://user-images.githubusercontent.com/89193/59800037-d9ec2580-92a2-11e9-9d56-100f48dd162f.png">

**Comment by vtbassmatt** [comment] 2019-06-20 11:10
Sorry to hear that :( Are you builds in a public project where we could take a look? The command-line task version is 2.151.1 but there are other variables which could be changing: agent version, image, etc.

**Comment by azooinmyluggage** [comment] 2019-06-20 12:48
Ralph pointed this out. I have routed it to the right team. Will revert as soon as we have a root cause.
Sorry for the pain it has caused.

**Comment by johnterickson** [comment] 2019-06-20 16:41
I've been able to repro this on my public project here: 

Found:
https://dev.azure.com/johnterickson/rust-lang/_build/results?buildId=555

```
##[section]Starting: Check rustc and cargo versions (before rustup install)
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.148.2
Author       : Microsoft Corporation
Help         : https://go.microsoft.com/fwlink/?LinkID=613738
==============================================================================
Generating script.
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/f2878cc3-27ae-4a9a-b007-0fe5bfdcea2e.sh
+ rustup toolchain list
stable-x86_64-unknown-linux-gnu (default)
+ rustc -V
rustc 1.34.2 (6c2484dc3 2019-05-13)
+ cargo -V
cargo 1.34.0 (6789d8a0a 2019-04-01)
+ ls
azure-pipelines.yml
Cargo.lock
Cargo.toml
LICENSE
README.md
src
##[section]Finishing: Check rustc and cargo versions (before rustup install)
```

vs not found:
https://dev.azure.com/johnterickson/rust-lang/_build/results?buildId=556
```
##[section]Starting: Check rustc and cargo versions (before rustup install)
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.148.2
Author       : Microsoft Corporation
Help         : https://go.microsoft.com/fwlink/?LinkID=613738
==============================================================================
Generating script.
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/b13086c3-86ff-4c6a-8e67-714902b4a695.sh
+ rustup toolchain list
/home/vsts/work/_temp/b13086c3-86ff-4c6a-8e67-714902b4a695.sh: line 2: rustup: command not found
+ rustc -V
/home/vsts/work/_temp/b13086c3-86ff-4c6a-8e67-714902b4a695.sh: line 3: rustc: command not found
+ cargo -V
/home/vsts/work/_temp/b13086c3-86ff-4c6a-8e67-714902b4a695.sh: line 4: cargo: command not found
+ ls
azure-pipelines.yml
Cargo.lock
Cargo.toml
LICENSE
README.md
src
##[section]Finishing: Check rustc and cargo versions (before rustup install)
```

both builds of https://github.com/johnterickson/cargo2junit/commit/d98711b98e5b5a3a1a9925ebf2a3bc326bfebece

**Comment by johnterickson** [comment] 2019-06-20 17:01
We're in a bit of a torn state because of where support was added in #900, where we are in the deployment, and the non-idempotency of rustup.

While this gets worked through, here's a snippet from https://github.com/johnterickson/cargo2junit/blob/master/azure-pipelines.yml to get you through the day:

```
variables:
  CHANNEL: stable
pool:
  vmImage:  $(VM_IMAGE)
strategy:
  matrix:
    x86_64-pc-windows-gnu:
      TARGET: x86_64-pc-windows-gnu
      VM_IMAGE: vs2017-win2016
    x86_64-pc-windows-msvc:
      TARGET: x86_64-pc-windows-msvc
      VM_IMAGE: vs2017-win2016
    osx-10.13-x86_64-apple-darwin:
      TARGET: x86_64-apple-darwin
      VM_IMAGE: macos-10.13
    x86_64-unknown-linux-gnu:
      TARGET: x86_64-unknown-linux-gnu
      VM_IMAGE: ubuntu-16.04
  - bash: |
      set -x
      curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path --default-toolchain none
      echo "##vso[task.prependpath]$HOME/.cargo/bin"
    displayName: Enusure rustup is installed
  - bash: |
      set -x
      rustup toolchain install --no-self-update $CHANNEL-$TARGET
      rustup default $CHANNEL-$TARGET
    displayName: Select toolchain
  - bash: |
      set -x
      rustup toolchain list
      rustc -V
      cargo -V
    displayName: Check rustc and cargo versions

**Comment by pasangh** [comment] 2019-06-20 18:15
Thanks for addressing this. The path variable wasn't set correctly. We have a fix which we are rolling out currently and ETA would be 6/22. I'll provide an update once it's out everywhere

**Comment by technosophos** [comment] 2019-06-20 23:54
Excellent! Thanks!

**Comment by pasangh** [comment] 2019-06-26 19:01
We rolled out the fix. Closing this issue.

**Closed by pasangh** 2019-06-26 19:01 UTC
