### ISSUE TITLE
Azure Powershell Az module

### ISSUE THREAD

**Issue by SamirFarhat** [Microsoft/azure-pipelines-image-generation#700] opened 2019-02-12 06:42 UTC
**Tool infomation**
Azure Powershell

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [x ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [ ] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
The new Azure Powershell module is no Az, Azure ARM will no longer receive udpates. When do you think you will update the hosted agents to support it ?
https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-1.2.0

**Comment by kmkumaran** [comment] 2019-02-14 03:17
Dupe of #660

**Closed by kmkumaran** 2019-02-14 03:17 UTC
Labels: area:Deployment/DBs/services, image:VS2017-Win2016, issue:Enhancement
