### ISSUE TITLE
Update NuGet

### ISSUE THREAD

**Issue by stannynuytkens** [Microsoft/azure-pipelines-image-generation#706] opened 2019-02-13 14:40 UTC
**Tool infomation**
- Tool name: **NuGet**
- Add or update? **Update**
- Desired version: **Latest stable? eg. 4.9.3**
- If this is an add request:
  - Brief description of tool: _N/A_
  - URL for tool's homepage: _N/A_

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [x] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [x] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [x] Other

Using [NuGetCommand@2](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops) results in getting version `2.146.0` of the task which gets us NuGet version `4.1.0.2450` which was [released April 2017](https://dist.nuget.org/tools.json).

I'm using this task to pack both PCL (legacy) and netstandard1.1 csproj files. Some projects have project references so I pack using `-IncludeReferencedProjects` but the netstandard1.1 csproj fails. This is how I noticed the outdated NuGet being used on the hosted environment... I decided to use the NuGet tool installer task and now everything packs fine (project references are updated to package references which is nice).

This has been asked [here](https://github.com/Microsoft/azure-pipelines-image-generation/issues/449) as well.

**Comment by DavidStaheli** [comment] 2019-02-19 17:17
Thanks a lot for requesting this @stannynuytkens.  This appears to be a duplicate of #449 which I believe is being worked on right now.  I will close this issue in favor of that one, but please feel free to reopen this if I have it wrong.

**Closed by DavidStaheli** 2019-02-19 17:17 UTC
Labels: area:Packages, issue:Enhancement
