### ISSUE TITLE
Add Chrome for testing to macOS image

### ISSUE THREAD

**Issue by martincostello** [microsoft/azure-pipelines-image-generation#250] opened 2018-09-23 10:05 UTC
Similar to #47 and #181, Chrome should be installed onto the hosted macOS image to allow for browser automation tests.

Whilst it can be installed manually with something like the below YAML, this takes over a minute, which adds up over many builds.

```yaml
- script: |
    brew install brew-cask
    brew cask install google-chrome
```

**Comment by ekrapfl** [comment] 2018-10-10 14:03
I agree that it would be really helpful to have Chrome be pre-installed on the images.  Is there any timeline for when something like that could be added to the hosted images?

Thanks!

**Comment by DavidStaheli** [comment] 2018-11-21 17:08
Similar/duplicate of #307 that describes adding/updating Chrome on macOS and Windows.

**Comment by martincostello** [comment] 2018-11-21 17:11
I'd say different - that's asking for Chrome to be updated where it's already available (i.e. Windows and Linux).

macOS doesn't have Chrome at all right now.

**Comment by ekrapfl** [comment] 2018-11-28 15:05
Is there any update on if/when this might be added?  This is the only thing that is holding my organization back from fully embracing the MacOS hosted images.  I would imagine there are others like us.  Chrome is a requirement for our unit tests to run.

**Comment by molant** [comment] 2019-02-05 17:35
I've been using @martincostello approach for a while but sometimes it doesn't get installed correctly and my tests fail :(
@DavidStaheli anything we can do to make this happen?

**Comment by ekrapfl** [comment] 2019-02-15 13:18
Another workaround that can help is using puppeteer to install chrome as an npm package.
https://github.com/GoogleChrome/puppeteer

For us, that change amounted to this in our package.json:
`"puppeteer": "^1.12.2"`

And this in our karma.conf.js:
`process.env.CHROME_BIN = require("puppeteer").executablePath();`

**Comment by ccampo** [comment] 2019-04-03 08:25
I am also waiting for Chrome to come to the Hosted Mac OS agents. As a workaround I use the Ubuntu images.....but that is really only a workaround.

**Comment by martincostello** [comment] 2019-07-02 09:23
This should be actioned, not stale.

**Comment by ekrapfl** [comment] 2019-07-02 11:37
As I said, we have been using puppeteer to have chrome installed via npm during the build, and that has worked great for us.  It does seem like the MacOS image should have it, though.  Same as the windows one.

**Comment by martincostello** [comment] 2019-09-30 13:22
Not stale.

**Comment by martincostello** [comment] 2019-12-29 13:46
Not stale.

**Comment by nrajpurkar** [comment] 2019-12-29 21:25
@martincostello, thanks for keeping this issue open. As a heads-up, this will be coming with an image update in the new year.

**Comment by kaylangan** [comment] 2020-01-09 21:07
This work has been completed and is awaiting deployment. Follow https://github.com/actions/virtual-environments/issues/7 for updates.

**Closed by kaylangan** 2020-01-09 21:07 UTC
Labels: area:Testing/code coverage, image:macOS, issue:Enhancement
