### ISSUE TITLE
Compile Python binaries with shared option (all versions of Python, Ubuntu only)

### ISSUE THREAD

**Issue by schlomo** [microsoft/azure-pipelines-image-generation#225] opened 2018-09-06 22:10 UTC
Requesting Python 3.6 (because pyinstaller doesn't support 3.7 yet) leads to broken Python 3.6.5 without shared libraries.

VSTS YAML config:
```yaml
- phase: Build_Standalone_Binary_Linux
  queue:
    name: Hosted Linux Preview
    demands: sh
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6' 
      addToPath: true
  - task: ShellScript@2
    inputs:
      scriptPath: build.sh
```

The `build.sh` contains a call to `pyinstaller`, a Python tool to create a single-file executable packaging the Python interpreter, all modules and the script file itself. pyinstaller fails with this error:

```
2018-09-06T22:01:40.9783733Z 12385 INFO: Python library not in binary dependencies. Doing additional searching...
2018-09-06T22:01:41.0148819Z Traceback (most recent call last):
2018-09-06T22:01:41.0168599Z   File "/home/vsts/work/1/s/build/python/bin/pyinstaller", line 11, in <module>
2018-09-06T22:01:41.0188163Z     sys.exit(run())
2018-09-06T22:01:41.0214953Z   File "/home/vsts/work/1/s/build/python/lib/python3.6/site-packages/PyInstaller/__main__.py", line 94, in run
2018-09-06T22:01:41.0234829Z     run_build(pyi_config, spec_file, **vars(args))
2018-09-06T22:01:41.0254651Z   File "/home/vsts/work/1/s/build/python/lib/python3.6/site-packages/PyInstaller/__main__.py", line 46, in run_build
2018-09-06T22:01:41.0273927Z     PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
2018-09-06T22:01:41.0293840Z   File "/home/vsts/work/1/s/build/python/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 791, in main
2018-09-06T22:01:41.0312602Z     build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
2018-09-06T22:01:41.0332033Z   File "/home/vsts/work/1/s/build/python/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 737, in build
2018-09-06T22:01:41.0354836Z     exec(text, spec_namespace)
2018-09-06T22:01:41.0376867Z   File "<string>", line 16, in <module>
2018-09-06T22:01:41.0396549Z   File "/home/vsts/work/1/s/build/python/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 213, in __init__
2018-09-06T22:01:41.0416300Z     self.__postinit__()
2018-09-06T22:01:41.0436387Z   File "/home/vsts/work/1/s/build/python/lib/python3.6/site-packages/PyInstaller/building/datastruct.py", line 161, in __postinit__
2018-09-06T22:01:41.0457833Z     self.assemble()
2018-09-06T22:01:41.0477521Z   File "/home/vsts/work/1/s/build/python/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 545, in assemble
2018-09-06T22:01:41.0498572Z     self._check_python_library(self.binaries)
2018-09-06T22:01:41.0523282Z   File "/home/vsts/work/1/s/build/python/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 629, in _check_python_library
2018-09-06T22:01:41.0543537Z     raise IOError(msg)
2018-09-06T22:01:41.0562622Z OSError: Python library not found: libpython3.6m.so.1.0, libpython3.6mu.so.1.0, libpython3.6.so.1.0
2018-09-06T22:01:41.0583238Z This would mean your Python installation doesn't come with proper library files.
2018-09-06T22:01:41.0603751Z This usually happens by missing development package, or unsuitable build parameters of Python installation.
2018-09-06T22:01:41.0614295Z 
2018-09-06T22:01:41.0634093Z * On Debian/Ubuntu, you would need to install Python development packages
2018-09-06T22:01:41.0653800Z   * apt-get install python3-dev
2018-09-06T22:01:41.0675345Z   * apt-get install python-dev
2018-09-06T22:01:41.0696272Z * If you're building Python by yourself, please rebuild your Python with `--enable-shared` (or, `--enable-framework` on Darwin)
2018-09-06T22:01:41.0705581Z 
```

I did a search for the `libpython3.6*so*` files:
```
2018-09-06T21:49:07.6649577Z /usr/share/miniconda/pkgs/python-3.6.5-hc3d631a_2/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a
2018-09-06T21:49:07.6666021Z /usr/share/miniconda/pkgs/python-3.6.5-hc3d631a_2/lib/libpython3.6m.a
2018-09-06T21:49:07.6682428Z /usr/share/miniconda/pkgs/python-3.6.5-hc3d631a_2/lib/libpython3.6m.so.1.0
2018-09-06T21:49:07.6696543Z /usr/share/miniconda/pkgs/python-3.6.5-hc3d631a_2/lib/libpython3.6m.so.1
2018-09-06T21:49:07.6713307Z /usr/share/miniconda/pkgs/python-3.6.5-hc3d631a_2/lib/libpython3.6m.so
2018-09-06T21:49:07.6734218Z /usr/share/miniconda/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a
2018-09-06T21:49:07.6754299Z /usr/share/miniconda/lib/libpython3.6m.a
2018-09-06T21:49:07.6770871Z /usr/share/miniconda/lib/libpython3.6m.so.1.0
2018-09-06T21:49:07.6789138Z /usr/share/miniconda/lib/libpython3.6m.so.1
2018-09-06T21:49:07.6805250Z /usr/share/miniconda/lib/libpython3.6m.so
2018-09-06T21:49:07.6823475Z /opt/hostedtoolcache/Python/3.6.5/x64/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a
2018-09-06T21:49:07.6840399Z /opt/az/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a
2018-09-06T21:49:07.6855728Z /opt/az/lib/libpython3.6m.a
```

We can see clearly that there are no shared Python libraries in the **Python 3.6.5** directory `/opt/hostedtoolcache/Python/3.6.5/x64`

Can you please fix the hosted tool cache to also include the shared Python libraries for all Python versions?

**Comment by dakale** [comment] 2018-09-10 16:01
@brcrista Do you think this is something you can handle on the tools cache side? I havent looked very deeply into it yet, and we can discuss more, but the logs point to:
> 2018-09-06T22:01:41.0696272Z * If you're building Python by yourself, please rebuild your Python with `--enable-shared` (or, `--enable-framework` on Darwin)

I can add the `-dev` packages at a system level. But I think also solving this at the hosted tools cache is important to so builds dont need to modify library paths etc

**Comment by brcrista** [comment] 2018-09-10 17:20
Thanks.  It sounds like we should build with that flag.
@schlomo, in the meantime, does running `sudo apt-get install -y python3-dev` before running your `build.sh` unblock you?

**Comment by schlomo** [comment] 2018-09-11 18:52
@brcrista how would installing python3-dev in version 3.7.0 from the system help with the python 3.6.5 from the hosted tools cache?

I am wondering if this could be related to the Python 3.6.5 distribution that you are using. Was it compiled with shared library support? If not, then maybe you would have to switch to another Python distro that is compiled with shared libraries.

**Comment by brcrista** [comment] 2018-09-12 16:40
We build these versions of version from source and we need to pass that flag during the build.

I'll admit I'm not too familiar with how the shared lib interacts with a particular interpreter.  I thought perhaps you could install the package to get the .so file and copy it where it's needed as a temporary workaround.  But if the same .so needs to be consumed by the Python interpreter or something I understand the issue.

**Comment by schlomo** [comment] 2018-09-12 16:42
Could you update the source building process to add the `--enable-shared` option?

**Comment by brcrista** [comment] 2018-09-12 21:10
We are tracking that work on our end now, but it will take some time to roll out so it would be good to find a workaround.

There should be Python 3.6 installed globally on the Hosted Linux Preview image (call `python3` / `pip3`).  See if you can use that interpreter to run pyinstaller.  

(Normally I would recommend you always run a build with the Use Python Version task.  But for this phase where all you are doing is packaging and don't need to fan out to multiple versions, it shouldn't matter that much.)

**Comment by greengumby** [comment] 2018-12-17 10:30
Is there a workaround for this issue?

**Comment by brcrista** [comment] 2018-12-17 14:00
You can install Python yourself during the build, or run a self-hosted agent and install Python yourself on that machine.  In either case, you can just put Python in PATH and not bother with the Use Python Version task.

**Comment by greengumby** [comment] 2019-03-05 08:48
@brcrista Noticed this issue has been pushed to another sprint. How do I install python manually during the build process?

**Comment by brcrista** [comment] 2019-03-05 19:33
`sudo apt-get install -y python3-dev` should have what you need

**Comment by ahoereth** [comment] 2019-04-23 10:38
Any updates on this? Employing azure pipelines for a unified build pipeline over linux, mac and windows -- above workaround does not really help with that and is also stuck to python 3.5

**Comment by pramodk** [comment] 2019-05-05 21:02
Was trying azure-pipeline first time today and this issue has certainly gave me bad impression.
Would be great if this is fixed because python3.6/3.7-dev is such a basic for many projects! Spending hours to find the root cause is certainly not optimal for end users.

**Comment by kaylangan** [comment] 2019-05-06 17:22
@pramodk @ahoereth I apologize for the inconvenience. We've planned this work for this week. Once it's merged, it will take up to 3 weeks to deploy depending what ring your account is on. Thanks for your patience.

**Comment by kaylangan** [comment] 2019-05-23 13:37
We've updated our tool cache for Linux for Python versions:
- 2.7.16
- 3.4.10 (replaced 3.4.8)
- 3.5.7
- 3.6.8
- 3.7.3

This change should roll out with the M153 release.

**Closed by kaylangan** 2019-05-23 13:37 UTC
Labels: area:Python, image:Ubuntu, issue:Enhancement, status:Approved, status:Help wanted
